name: fpembed
channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - nicegui==3.14.0
  - optuna==4.8.0
  - pyyaml==6.0.3
  - altair==5.4.1
  - pandas==2.2.3
  - numpy==2.2.6
  - rdkit==2026.3.1
  - scikit-learn==1.7.2
  - tqdm==4.67.3
  - pip:
    - -e .
